### ISSUE TITLE
Can't Program more than one Roku TV

### ISSUE THREAD

**Issue by GoLiveBroadcast** [FUNKYJASPER2/StreamDeck-Roku-Remote-Plugin#9] opened 2024-02-24 00:34 UTC
I am trying to add on/off function for two different televisions using separate buttons. I have 4 buttons so far - one TV has an on and an off button assigned, and the other does as well. When changing the IP address for a button - for argument sake let's say the 'ON' button for TV1, the IP address changes for ALL of the buttons.

**Comment by FUNKYJASPER2** [comment] 2024-02-28 04:54
Closed as it is a duplicate of: [https://github.com/FUNKYJASPER2/StreamDeck-Roku-Remote-Plugin/issues/1](https://github.com/FUNKYJASPER2/StreamDeck-Roku-Remote-Plugin/issues/1)

**Closed by FUNKYJASPER2** 2024-02-28 04:54 UTC
